
--DB1 Words
CREATE TABLE WORDS (
  WORD_ID INTEGER IDENTITY (1,1) PRIMARY KEY,
  WORDS VARCHAR (5)
  );

SELECT WORDS FROM WORDS  
ORDER BY RAND ( )  
LIMIT 1  

--DB2 Users
CREATE TABLE USERS (
USER_ID Integer IDENTITY (1,1) PRIMARY KEY,
USERNAME text NOT NULL (20),
NAME text,
AGE Integer
);

INSERT INTO USERS (USERNAME =?, NAME= ?, AGE= ?);

SELECT COUNT (USERNAME) FROM USERS;



--DB3 Results
CREATE TABLE RESULTS (
GAME_ID INTEGER IDENTITY (1,1) PRIMARY KEY,
USER_ID FOREIGN KEY,
WORD_ID FOREIGN KEY,
GUESSES Integer,
WON Integer --will save 1 or 0
  );
  
INSERT INTO RESULTS (USER_ID=?, GUESSES=?, WON=?);

SELECT COUNT (GAME_ID) FROM RESULTS WHERE USER_ID =?;
SELECT COUNT (WON) FROM RESULTS WHERE USER_ID=? AND WON>0;
SELECT 

